# Generated by Django 4.0.3 on 2022-04-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='training',
        ),
        migrations.AddField(
            model_name='comment',
            name='training_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingz_app.trainingday'),
        ),
    ]
