# Generated by Django 4.0.3 on 2022-03-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutblock',
            name='duration',
            field=models.SmallIntegerField(),
        ),
    ]
