# Generated by Django 4.0.3 on 2022-04-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingz_app', '0002_remove_comment_training_comment_training_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='training_day',
        ),
        migrations.AddField(
            model_name='comment',
            name='training_day',
            field=models.ManyToManyField(to='trainingz_app.trainingday'),
        ),
    ]
