# Generated by Django 4.0.3 on 2022-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingz_app', '0004_remove_comment_training_day_comment_training_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingday',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
