from django.urls import path

from trainingz_app import views

urlpatterns = [
    path(
        "add_workout_block/",
        views.AddWorkoutBlockView.as_view(),
        name="add_workout_block",
    ),
    path(
        "list_workout_blocks/",
        views.ShowWorkoutBlocksView.as_view(),
        name="list_workout_blocks",
    ),
    path(
        "workout_block/<int:id>/",
        views.ShowDetailWorkoutBlockView.as_view(),
        name="detail_workout_block",
    ),
    path(
        "update_workout_block/<int:id>/",
        views.UpdateWorkoutBlockView.as_view(),
        name="update_workout_block",
    ),
    path(
        "delete_workout_block/<int:id>/",
        views.DeleteWorkoutBlockView.as_view(),
        name="delete_workout_block",
    ),
    path(
        "add_training/", views.AddTrainingView.as_view(), name="add_training"
    ),
    path(
        "list_trainings/",
        views.ShowTrainingsView.as_view(),
        name="list_trainings",
    ),
    path(
        "training/<int:id>/",
        views.ShowDetailTrainingView.as_view(),
        name="detail_training",
    ),
    path(
        "update_training/<int:id>/",
        views.UpdateTrainingView.as_view(),
        name="update_training",
    ),
    path(
        "delete_training/<int:id>/",
        views.DeleteTraining.as_view(),
        name="delete_training",
    ),
    path(
        "add_training_week/",
        views.AddTrainingWeekView.as_view(),
        name="add_training_week",
    ),
    path(
        "list_training_weeks/",
        views.ShowTrainingWeeksView.as_view(),
        name="list_training_weeks",
    ),
    path(
        "training_week/<int:id>/",
        views.ShowDetailTrainingWeekView.as_view(),
        name="detail_training_week",
    ),
    path(
        "update_training_week/<int:id>/",
        views.UpdateTrainingWeekView.as_view(),
        name="update_training_week",
    ),
    path(
        "delete_training_week/<int:id>/",
        views.DeleteTrainingWeek.as_view(),
        name="delete_training_week",
    ),
    path("add_comment/", views.AddCommentView.as_view(), name="add_comment"),
]
